app/models/artifact.rb, app/models/booking.rb, app/models/user.rb, db/migrate/20181112114108_create_users.rb, db/migrate/20181112114607_create_artifacts.rb, db/migrate/20181112114926_create_bookings.rb, test/models/artifact_test.rb, test/models/booking_test.rb, test/models/user_test.rb
Please review my model code, in app > models  &  app > db > migrate
=> initial models created

app/models/artifact.rb, db/migrate/20181112203520_change_column_default_in_artifact.rb, db/migrate/20181112203708_change_discount_column_default_in_artifact.rb, db/schema.rb
Added validation to artifact model - still not polished
=> Artifact validation

app/controllers/artifacts_controller.rb, app/views/artifacts/show.html.erb, app/views/shared/_add_artifact.html.erb
Artifact new-create coded and tested.  New action works and redirects to show page
=> Artifact controller

db/seeds.rb
seed base file created with some.... 'fancy' interface features which I'd like to keep and I am happy to demonstrate and explain
=> seed file base created - condition seeds tested

db/migrate/20181113051129_change_column_in_artifacts.rb, db/schema.rb
I changed the field name so that it appears better and more clear for the user using the simple_form....
immediate bug found... will add new branch and pull directly
=> discount changed to percent_discount

app/controllers/bookings_controller.rb, app/views/bookings/create.html.erb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, config/routes.rb, test/controllers/bookings_controller_test.rb
created new bookings controller
=> booking controller created

app/controllers/dashboards_controller.rb, app/views/dashboards/index.html.erb, config/routes.rb, test/controllers/dashboards_controller_test.rb
=> dashboards controller created

app/controllers/dashboards_controller.rb, app/views/dashboards/index.html.erb
the dashboard controller is up and the index action directs to the created view page. Must be logged in to view it, as you would expect
=> dashboard#index action up and running

db/migrate/20181113075151_add_photo_to_user.rb, db/schema.rb
Added a photo column to the user table so we can add image links, so we can utilize an avatar functionality
=> photo column added to user

app/models/artifact.rb, db/seeds.rb
I adjusted the see file little to ensure that the images show and a database drop is no long required. Also I designated specific users on the artifacts to ensure all had at least one artifact - though unlikely using the sample could result in a user not owning an artifact
=> Seed adjustments

db/migrate/20181114045153_add_booking_status_column_to_bookings.rb, db/schema.rb
I added the booking status booleans so we can add functionality later. As always remember to never update to a working branch
=> 2 boolean booking status fields added to DB

app/views/layouts/application.html.erb
=> site title changed to antiquity direct

app/helpers/application_helper.rb, app/views/shared/_navbar.html.erb
Upon the recommendation of Hans, I removed the if-else logic from the navbar, which was used to display the users photo if it existed - it was moved to 'helper' folder
=> moved the avatar image logic to a help method

app/views/artifacts/new.html.erb, app/views/shared/_add_artifact.html.erb
There was a missing ruby end tag on the add article form which was causing it to break. that was fixed. I also lightly polished the html in the form and on the 'new' page to make it render correctly - my tags weren't closed properly
=> _add_artifact form fixed and some rendering bugs on 'new' page

app/helpers/application_helper.rb
=> variable bug fix in help for avatar image

app/controllers/application_controller.rb, app/controllers/bookings_controller.rb, app/views/artifacts/show.html.erb, config/routes.rb
Hid booking form in show page when user not logged in.
Logging in from the show page does not redirect user to landing page.
=> Display booking form only when logged in

app/controllers/bookings_controller.rb, app/views/shared/_booking_form.html.erb, config/routes.rb, db/migrate/20181114101728_add_decline_booking_status_column_to_bookings.rb
booking form was un-nested and an additional field added to the bookings table for future functionality
=> Booking form backend

app/views/artifacts/index.html.erb, app/views/artifacts/show.html.erb, db/schema.rb
=> implemented grid for index page

Gemfile, Gemfile.lock, db/schema.rb, db/seeds.rb
New seed file, tested ok - now with 12 artifacts and 30 bookings randomly generated
=> new seed file for more artifacts and bookings

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/layouts/_index.scss, app/assets/stylesheets/layouts/_show.scss, app/views/artifacts/index.html.erb, app/views/artifacts/show.html.erb, db/seeds.rb
Worked on:
- index page to make cards a link to show page, ordered cards to 3 per row in container.
- show page divided in 2 between image and text.
- text includes more useful info.
=> Index page design

app/assets/stylesheets/pages/_dashboard.scss, app/controllers/dashboards_controller.rb, app/helpers/application_helper.rb, app/views/dashboards/index.html.erb
Dramatic improvment in dashbord - not fully developed
=> dashboard has now better dynamic content and style

db/seeds.rb
trying to clean the seed - didn't seed properly on heroku
=> attempting to fix seed errors on heroku

db/seeds.rb
found small spelling difference in seed file
=> small type in seed file

app/views/shared/_navbar.html.erb
=> small bug in navbar links corected

app/views/artifacts/index.html.erb
=> row bug in index page fixed

app/views/artifacts/index.html.erb
=> another attempt to fish the rows

app/views/artifacts/index.html.erb
=> syntax error fix

app/controllers/bookings_controller.rb, app/controllers/dashboards_controller.rb, app/models/booking.rb, app/views/dashboards/index.html.erb, config/routes.rb
the dashboard is visible again, but there is a logic problem, owners can book their own artifacts
I am going to address that issue now
=> Dashboard again

app/models/booking.rb
User can no longer book own item
=> booking validation now restricts from booking your own item

db/seeds.rb
Indiana jones now a user, he has 3 products and seed file will not allow users to have bookings of their own stuff
=> seed file improvements: 1 more user and 3 more artifacts

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb
Added underline effect to navbar links.
Commented out <div class="alert"> on homepage that cause the footer to have a gap.
=> added underline effect to navbar

app/helpers/application_helper.rb
=> € symbol moved to behind the price

db/seeds.rb
tiny bug in seed file - new `rails db:seed` will fix the issue
=> tiny typo in image link for cross of coronado

app/assets/javascripts/application.js, app/assets/stylesheets/layouts/_show.scss, app/controllers/artifacts_controller.rb, app/models/artifact_type.rb, app/views/artifacts/index.html.erb
Added a filter by category bar in index page (courtesy of Hans).
=> Category filter attempt

app/assets/stylesheets/layouts/_index.scss, app/views/artifacts/index.html.erb, db/seeds.rb
styled categories filter bar
corrected typo in seeds skulpture --> sculpture
=> changed typo in seeds (sculpture) and styled categories bar

app/assets/stylesheets/components/_login_form.scss, app/views/artifacts/show.html.erb
rounded edges in form (login/sign up)
=> Style details

app/assets/stylesheets/components/_artifact-grid.scss, app/assets/stylesheets/components/_forms.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/layouts/_index.scss, app/views/artifacts/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/shared/_add_artifact.html.erb
grid layout for add new artifact page.
Missing disclaimer
=> grid layout add new artifact page

db/seeds.rb
=> spelling bug found in seed file

app/views/artifacts/new.html.erb
nearly finished add-new page. missing icons for disclaimer
=> eliminated full-stop inconsistency in disclaimer
